name: Supabase IPv4 Add-on

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform: enable or disable'
        required: true
        default: 'enable'
        type: string

jobs:
  manage-ipv4:
    runs-on: ubuntu-latest
    env:
      PROJECT_REF: ${{ secrets.SUPABASE_PROJECT_REF }}
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
    steps:
      - name: Check inputs
        run: |
          echo "Action: ${{ github.event.inputs.action }}"
      - name: Show current add-ons
        run: |
          if [ -z "${SUPABASE_ACCESS_TOKEN:-}" ] || [ -z "${PROJECT_REF:-}" ]; then
            echo "ERROR: SUPABASE_ACCESS_TOKEN and SUPABASE_PROJECT_REF must be set as repository secrets"
            exit 2
          fi
          curl -s -X GET "https://api.supabase.com/v1/projects/${PROJECT_REF}/billing/addons" \
            -H "Authorization: Bearer ${SUPABASE_ACCESS_TOKEN}" \
            -H "Accept: application/json" | jq .
      - name: Enable IPv4 via API
        if: ${{ github.event.inputs.action == 'enable' }}
        run: |
          echo "Enabling IPv4 add-on for project ${PROJECT_REF}"
          curl -s -X POST "https://api.supabase.com/v1/projects/${PROJECT_REF}/addons" \
            -H "Authorization: Bearer ${SUPABASE_ACCESS_TOKEN}" \
            -H "Content-Type: application/json" \
            -d '{"addon_type":"ipv4"}' | jq .
      - name: Disable IPv4 via API
        if: ${{ github.event.inputs.action == 'disable' }}
        run: |
          echo "Disabling IPv4 add-on for project ${PROJECT_REF}"
          curl -s -X DELETE "https://api.supabase.com/v1/projects/${PROJECT_REF}/billing/addons/ipv4" \
            -H "Authorization: Bearer ${SUPABASE_ACCESS_TOKEN}" \
            -H "Accept: application/json" | jq .
